/*
Navicat Oracle Data Transfer
Oracle Client Version : 12.1.0.2.0

Source Server         : LOCAL_LOTTERY
Source Server Version : 110200
Source Host           : localhost:1521
Source Schema         : ANALYZERLOTTERY

Target Server Type    : ORACLE
Target Server Version : 110200
File Encoding         : 65001

Date: 2018-11-13 15:06:09
*/


-- ----------------------------
-- Table structure for "ANALYZERLOTTERY"."ASSIGNROLESTOUSER"
-- ----------------------------
DROP TABLE "ANALYZERLOTTERY"."ASSIGNROLESTOUSER";
CREATE TABLE "ANALYZERLOTTERY"."ASSIGNROLESTOUSER" (
"ARU_ID" NUMBER NOT NULL ,
"R_ID" NUMBER NOT NULL ,
"U_ID" VARCHAR2(255 BYTE) NOT NULL ,
"ARU_ACTIVE" VARCHAR2(50 BYTE) DEFAULT 'ACTIVE'  NOT NULL ,
"MODIFYDATE" DATE DEFAULT SYSDATE  NULL ,
"MODIFYBY" VARCHAR2(255 BYTE) DEFAULT 'SYSTEM'  NULL ,
"CREATEDATETIME" DATE DEFAULT SYSDATE  NULL ,
"CREATEBY" VARCHAR2(255 BYTE) DEFAULT 'SYSTEM'  NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON COLUMN "ANALYZERLOTTERY"."ASSIGNROLESTOUSER"."ARU_ACTIVE" IS 'Value = ACTIVE / INACTIVE';

-- ----------------------------
-- Records of ASSIGNROLESTOUSER
-- ----------------------------
INSERT INTO "ANALYZERLOTTERY"."ASSIGNROLESTOUSER" VALUES ('1', '1', 'U01', 'ACTIVE', TO_DATE('2018-11-12 10:58:35', 'YYYY-MM-DD HH24:MI:SS'), 'SYSTEM', TO_DATE('2018-11-12 10:58:35', 'YYYY-MM-DD HH24:MI:SS'), 'SYSTEM');
INSERT INTO "ANALYZERLOTTERY"."ASSIGNROLESTOUSER" VALUES ('4', '2', 'U01', 'ACTIVE', TO_DATE('2018-11-12 11:00:13', 'YYYY-MM-DD HH24:MI:SS'), 'SYSTEM', TO_DATE('2018-11-12 11:00:13', 'YYYY-MM-DD HH24:MI:SS'), 'SYSTEM');

-- ----------------------------
-- Table structure for "ANALYZERLOTTERY"."OPERATIONCOMMAND"
-- ----------------------------
DROP TABLE "ANALYZERLOTTERY"."OPERATIONCOMMAND";
CREATE TABLE "ANALYZERLOTTERY"."OPERATIONCOMMAND" (
"OC_ID" NUMBER NOT NULL ,
"OC_NAME" VARCHAR2(255 BYTE) NOT NULL ,
"OC_DESCRIPTION" VARCHAR2(255 BYTE) NULL ,
"OC_SERVICEVALUE" VARCHAR2(255 BYTE) NULL ,
"OC_SCRIPTVALUE" VARCHAR2(255 BYTE) NULL ,
"OC_PAGE" VARCHAR2(255 BYTE) NULL ,
"OC_VALUE" VARCHAR2(255 BYTE) NULL ,
"OC_ACTIVE" VARCHAR2(255 BYTE) DEFAULT 'ACTIVE'  NOT NULL ,
"MODIFYDATE" DATE DEFAULT SYSDATE  NULL ,
"MODIFYBY" VARCHAR2(255 BYTE) DEFAULT 'SYSTEM'  NULL ,
"CREATEDATETIME" DATE DEFAULT SYSDATE  NULL ,
"CREATEBY" VARCHAR2(255 BYTE) DEFAULT 'SYSTEM'  NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Records of OPERATIONCOMMAND
-- ----------------------------
INSERT INTO "ANALYZERLOTTERY"."OPERATIONCOMMAND" VALUES ('1', 'BUY2', null, null, null, null, null, 'ACTIVE', TO_DATE('2018-11-13 15:03:30', 'YYYY-MM-DD HH24:MI:SS'), 'SYSTEM', TO_DATE('2018-11-13 15:03:30', 'YYYY-MM-DD HH24:MI:SS'), 'SYSTEM');

-- ----------------------------
-- Table structure for "ANALYZERLOTTERY"."ROLES"
-- ----------------------------
DROP TABLE "ANALYZERLOTTERY"."ROLES";
CREATE TABLE "ANALYZERLOTTERY"."ROLES" (
"R_ID" NUMBER NOT NULL ,
"R_NAME" VARCHAR2(255 BYTE) NOT NULL ,
"R_DESCRIPTION" VARCHAR2(255 BYTE) NULL ,
"R_ACTIVE" VARCHAR2(50 BYTE) DEFAULT 'ACTIVE'  NOT NULL ,
"MODIFYDATE" DATE DEFAULT SYSDATE  NULL ,
"MODIFYBY" VARCHAR2(255 BYTE) DEFAULT 'SYSTEM'  NULL ,
"CREATEDATETIME" DATE DEFAULT SYSDATE  NULL ,
"CREATEBY" VARCHAR2(255 BYTE) DEFAULT 'SYSTEM'  NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON COLUMN "ANALYZERLOTTERY"."ROLES"."R_ACTIVE" IS 'Value = ACTIVE / INACTIVE';

-- ----------------------------
-- Records of ROLES
-- ----------------------------
INSERT INTO "ANALYZERLOTTERY"."ROLES" VALUES ('1', 'Administrator', 'Management and control System.', 'ACTIVE', TO_DATE('2018-11-12 10:48:18', 'YYYY-MM-DD HH24:MI:SS'), 'SYSTEM', TO_DATE('2018-11-12 10:48:18', 'YYYY-MM-DD HH24:MI:SS'), 'SYSTEM');
INSERT INTO "ANALYZERLOTTERY"."ROLES" VALUES ('2', '2Number', 'Operation 2 number.', 'ACTIVE', TO_DATE('2018-11-12 10:48:48', 'YYYY-MM-DD HH24:MI:SS'), 'SYSTEM', TO_DATE('2018-11-12 10:48:48', 'YYYY-MM-DD HH24:MI:SS'), 'SYSTEM');
INSERT INTO "ANALYZERLOTTERY"."ROLES" VALUES ('3', '3Number', 'Operation 3 number.', 'ACTIVE', TO_DATE('2018-11-12 10:48:48', 'YYYY-MM-DD HH24:MI:SS'), 'SYSTEM', TO_DATE('2018-11-12 10:48:48', 'YYYY-MM-DD HH24:MI:SS'), 'SYSTEM');

-- ----------------------------
-- Table structure for "ANALYZERLOTTERY"."ROLETAKECOMMAND"
-- ----------------------------
DROP TABLE "ANALYZERLOTTERY"."ROLETAKECOMMAND";
CREATE TABLE "ANALYZERLOTTERY"."ROLETAKECOMMAND" (
"RTC_ID" NUMBER NOT NULL ,
"OC_ID" NUMBER NOT NULL ,
"R_ID" NUMBER NOT NULL ,
"RTC_ACTIVE" VARCHAR2(255 BYTE) DEFAULT 'ACTIVE'  NOT NULL ,
"MODIFYDATE" DATE DEFAULT SYSDATE  NULL ,
"MODIFYBY" VARCHAR2(255 BYTE) DEFAULT 'SYSTEM'  NULL ,
"CREATEDATETIME" DATE DEFAULT SYSDATE  NULL ,
"CREATEBY" VARCHAR2(255 BYTE) DEFAULT 'SYSTEM'  NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Records of ROLETAKECOMMAND
-- ----------------------------
INSERT INTO "ANALYZERLOTTERY"."ROLETAKECOMMAND" VALUES ('1', '1', '1', 'ACTIVE', TO_DATE('2018-11-13 15:04:43', 'YYYY-MM-DD HH24:MI:SS'), 'SYSTEM', TO_DATE('2018-11-13 15:04:43', 'YYYY-MM-DD HH24:MI:SS'), 'SYSTEM');

-- ----------------------------
-- Table structure for "ANALYZERLOTTERY"."TOKENLOGIN"
-- ----------------------------
DROP TABLE "ANALYZERLOTTERY"."TOKENLOGIN";
CREATE TABLE "ANALYZERLOTTERY"."TOKENLOGIN" (
"TL_TOKEN" VARCHAR2(255 BYTE) NOT NULL ,
"U_ID" VARCHAR2(255 BYTE) NOT NULL ,
"EXPIRY_DATE" DATE NOT NULL ,
"MODIFYDATE" DATE DEFAULT SYSDATE  NULL ,
"MODIFYBY" VARCHAR2(255 BYTE) DEFAULT 'SYSTEM'  NULL ,
"CREATEDATETIME" DATE DEFAULT SYSDATE  NULL ,
"CREATEBY" VARCHAR2(255 BYTE) DEFAULT 'SYSTEM'  NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Records of TOKENLOGIN
-- ----------------------------
INSERT INTO "ANALYZERLOTTERY"."TOKENLOGIN" VALUES ('7a4b758e-cc2e-4ff4-9e52-7ba07520c168', 'U01', TO_DATE('2018-11-13 01:21:52', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2018-11-09 17:21:52', 'YYYY-MM-DD HH24:MI:SS'), 'SYSTEM', TO_DATE('2018-11-09 17:21:52', 'YYYY-MM-DD HH24:MI:SS'), 'SYSTEM');

-- ----------------------------
-- Table structure for "ANALYZERLOTTERY"."USERS"
-- ----------------------------
DROP TABLE "ANALYZERLOTTERY"."USERS";
CREATE TABLE "ANALYZERLOTTERY"."USERS" (
"U_ID" VARCHAR2(255 BYTE) NOT NULL ,
"U_USERNAME" VARCHAR2(255 BYTE) NOT NULL ,
"U_PASSWORD" VARCHAR2(255 BYTE) NOT NULL ,
"U_DISPLAYNAME" VARCHAR2(255 BYTE) NULL ,
"U_DESCRIPTION" VARCHAR2(255 BYTE) NULL ,
"U_ACTIVE" VARCHAR2(255 BYTE) DEFAULT 'ACTIVE'  NOT NULL ,
"MODIFYDATE" DATE DEFAULT SYSDATE  NULL ,
"MODIFYBY" VARCHAR2(255 BYTE) DEFAULT 'SYSTEM'  NULL ,
"CREATEDATETIME" DATE DEFAULT SYSDATE  NULL ,
"CREATEBY" VARCHAR2(255 BYTE) DEFAULT 'SYSTEM'  NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON COLUMN "ANALYZERLOTTERY"."USERS"."U_ACTIVE" IS 'Value = ACTIVE / INACTIVE';

-- ----------------------------
-- Records of USERS
-- ----------------------------
INSERT INTO "ANALYZERLOTTERY"."USERS" VALUES ('U01', 'USERNAME01', '123', 'Username 01', 'Test username 01', 'ACTIVE', TO_DATE('2018-10-31 16:27:53', 'YYYY-MM-DD HH24:MI:SS'), 'SYSTEM', TO_DATE('2018-10-31 16:27:53', 'YYYY-MM-DD HH24:MI:SS'), 'SYSTEM');

-- ----------------------------
-- Sequence structure for "ANALYZERLOTTERY"."ARU_SEQUENCE"
-- ----------------------------
DROP SEQUENCE "ANALYZERLOTTERY"."ARU_SEQUENCE";
CREATE SEQUENCE "ANALYZERLOTTERY"."ARU_SEQUENCE"
 INCREMENT BY 1
 MINVALUE 1
 MAXVALUE 999999
 START WITH 21
 CACHE 20;

-- ----------------------------
-- Sequence structure for "ANALYZERLOTTERY"."DEMO_CUST_SEQ"
-- ----------------------------
DROP SEQUENCE "ANALYZERLOTTERY"."DEMO_CUST_SEQ";
CREATE SEQUENCE "ANALYZERLOTTERY"."DEMO_CUST_SEQ"
 INCREMENT BY 1
 MINVALUE 1
 MAXVALUE 9999999999999999999999999999
 START WITH 21
 CACHE 20;

-- ----------------------------
-- Sequence structure for "ANALYZERLOTTERY"."DEMO_ORD_SEQ"
-- ----------------------------
DROP SEQUENCE "ANALYZERLOTTERY"."DEMO_ORD_SEQ";
CREATE SEQUENCE "ANALYZERLOTTERY"."DEMO_ORD_SEQ"
 INCREMENT BY 1
 MINVALUE 1
 MAXVALUE 9999999999999999999999999999
 START WITH 11
 CACHE 20;

-- ----------------------------
-- Sequence structure for "ANALYZERLOTTERY"."DEMO_ORDER_ITEMS_SEQ"
-- ----------------------------
DROP SEQUENCE "ANALYZERLOTTERY"."DEMO_ORDER_ITEMS_SEQ";
CREATE SEQUENCE "ANALYZERLOTTERY"."DEMO_ORDER_ITEMS_SEQ"
 INCREMENT BY 1
 MINVALUE 1
 MAXVALUE 9999999999999999999999999999
 START WITH 61
 CACHE 20;

-- ----------------------------
-- Sequence structure for "ANALYZERLOTTERY"."DEMO_PROD_SEQ"
-- ----------------------------
DROP SEQUENCE "ANALYZERLOTTERY"."DEMO_PROD_SEQ";
CREATE SEQUENCE "ANALYZERLOTTERY"."DEMO_PROD_SEQ"
 INCREMENT BY 1
 MINVALUE 1
 MAXVALUE 9999999999999999999999999999
 START WITH 21
 CACHE 20;

-- ----------------------------
-- Sequence structure for "ANALYZERLOTTERY"."DEMO_USERS_SEQ"
-- ----------------------------
DROP SEQUENCE "ANALYZERLOTTERY"."DEMO_USERS_SEQ";
CREATE SEQUENCE "ANALYZERLOTTERY"."DEMO_USERS_SEQ"
 INCREMENT BY 1
 MINVALUE 1
 MAXVALUE 9999999999999999999999999999
 START WITH 21
 CACHE 20;

-- ----------------------------
-- Sequence structure for "ANALYZERLOTTERY"."OC_SEQUENCE"
-- ----------------------------
DROP SEQUENCE "ANALYZERLOTTERY"."OC_SEQUENCE";
CREATE SEQUENCE "ANALYZERLOTTERY"."OC_SEQUENCE"
 INCREMENT BY 1
 MINVALUE 1
 MAXVALUE 999999
 START WITH 21
 CACHE 20;

-- ----------------------------
-- Sequence structure for "ANALYZERLOTTERY"."RID_SEQUENCE"
-- ----------------------------
DROP SEQUENCE "ANALYZERLOTTERY"."RID_SEQUENCE";
CREATE SEQUENCE "ANALYZERLOTTERY"."RID_SEQUENCE"
 INCREMENT BY 1
 MINVALUE 1
 MAXVALUE 999999
 START WITH 21
 CACHE 20;

-- ----------------------------
-- Sequence structure for "ANALYZERLOTTERY"."RTC_SEQUENCE"
-- ----------------------------
DROP SEQUENCE "ANALYZERLOTTERY"."RTC_SEQUENCE";
CREATE SEQUENCE "ANALYZERLOTTERY"."RTC_SEQUENCE"
 INCREMENT BY 1
 MINVALUE 1
 MAXVALUE 999999
 START WITH 21
 CACHE 20;

-- ----------------------------
-- Indexes structure for table ASSIGNROLESTOUSER
-- ----------------------------

-- ----------------------------
-- Checks structure for table "ANALYZERLOTTERY"."ASSIGNROLESTOUSER"
-- ----------------------------
ALTER TABLE "ANALYZERLOTTERY"."ASSIGNROLESTOUSER" ADD CHECK ("ARU_ID" IS NOT NULL);
ALTER TABLE "ANALYZERLOTTERY"."ASSIGNROLESTOUSER" ADD CHECK ("R_ID" IS NOT NULL);
ALTER TABLE "ANALYZERLOTTERY"."ASSIGNROLESTOUSER" ADD CHECK ("U_ID" IS NOT NULL);
ALTER TABLE "ANALYZERLOTTERY"."ASSIGNROLESTOUSER" ADD CHECK ("ARU_ACTIVE" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table "ANALYZERLOTTERY"."ASSIGNROLESTOUSER"
-- ----------------------------
ALTER TABLE "ANALYZERLOTTERY"."ASSIGNROLESTOUSER" ADD PRIMARY KEY ("ARU_ID");

-- ----------------------------
-- Indexes structure for table OPERATIONCOMMAND
-- ----------------------------

-- ----------------------------
-- Checks structure for table "ANALYZERLOTTERY"."OPERATIONCOMMAND"
-- ----------------------------
ALTER TABLE "ANALYZERLOTTERY"."OPERATIONCOMMAND" ADD CHECK ("OC_ID" IS NOT NULL);
ALTER TABLE "ANALYZERLOTTERY"."OPERATIONCOMMAND" ADD CHECK ("OC_NAME" IS NOT NULL);
ALTER TABLE "ANALYZERLOTTERY"."OPERATIONCOMMAND" ADD CHECK ("OC_ACTIVE" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table "ANALYZERLOTTERY"."OPERATIONCOMMAND"
-- ----------------------------
ALTER TABLE "ANALYZERLOTTERY"."OPERATIONCOMMAND" ADD PRIMARY KEY ("OC_ID");

-- ----------------------------
-- Indexes structure for table ROLES
-- ----------------------------

-- ----------------------------
-- Checks structure for table "ANALYZERLOTTERY"."ROLES"
-- ----------------------------
ALTER TABLE "ANALYZERLOTTERY"."ROLES" ADD CHECK ("R_ID" IS NOT NULL);
ALTER TABLE "ANALYZERLOTTERY"."ROLES" ADD CHECK ("R_NAME" IS NOT NULL);
ALTER TABLE "ANALYZERLOTTERY"."ROLES" ADD CHECK ("R_ACTIVE" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table "ANALYZERLOTTERY"."ROLES"
-- ----------------------------
ALTER TABLE "ANALYZERLOTTERY"."ROLES" ADD PRIMARY KEY ("R_ID");

-- ----------------------------
-- Indexes structure for table ROLETAKECOMMAND
-- ----------------------------

-- ----------------------------
-- Checks structure for table "ANALYZERLOTTERY"."ROLETAKECOMMAND"
-- ----------------------------
ALTER TABLE "ANALYZERLOTTERY"."ROLETAKECOMMAND" ADD CHECK ("RTC_ID" IS NOT NULL);
ALTER TABLE "ANALYZERLOTTERY"."ROLETAKECOMMAND" ADD CHECK ("OC_ID" IS NOT NULL);
ALTER TABLE "ANALYZERLOTTERY"."ROLETAKECOMMAND" ADD CHECK ("R_ID" IS NOT NULL);
ALTER TABLE "ANALYZERLOTTERY"."ROLETAKECOMMAND" ADD CHECK ("RTC_ACTIVE" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table "ANALYZERLOTTERY"."ROLETAKECOMMAND"
-- ----------------------------
ALTER TABLE "ANALYZERLOTTERY"."ROLETAKECOMMAND" ADD PRIMARY KEY ("RTC_ID");

-- ----------------------------
-- Indexes structure for table TOKENLOGIN
-- ----------------------------

-- ----------------------------
-- Checks structure for table "ANALYZERLOTTERY"."TOKENLOGIN"
-- ----------------------------
ALTER TABLE "ANALYZERLOTTERY"."TOKENLOGIN" ADD CHECK ("TL_TOKEN" IS NOT NULL);
ALTER TABLE "ANALYZERLOTTERY"."TOKENLOGIN" ADD CHECK ("U_ID" IS NOT NULL);
ALTER TABLE "ANALYZERLOTTERY"."TOKENLOGIN" ADD CHECK ("EXPIRY_DATE" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table "ANALYZERLOTTERY"."TOKENLOGIN"
-- ----------------------------
ALTER TABLE "ANALYZERLOTTERY"."TOKENLOGIN" ADD PRIMARY KEY ("TL_TOKEN");

-- ----------------------------
-- Indexes structure for table USERS
-- ----------------------------
CREATE INDEX "ANALYZERLOTTERY"."INDEX_DISPLAYNAME"
ON "ANALYZERLOTTERY"."USERS" ("U_DISPLAYNAME" ASC)
LOGGING
VISIBLE;
CREATE INDEX "ANALYZERLOTTERY"."INDEX_USERNAME"
ON "ANALYZERLOTTERY"."USERS" ("U_USERNAME" ASC)
LOGGING
VISIBLE;

-- ----------------------------
-- Checks structure for table "ANALYZERLOTTERY"."USERS"
-- ----------------------------
ALTER TABLE "ANALYZERLOTTERY"."USERS" ADD CHECK ("U_ID" IS NOT NULL);
ALTER TABLE "ANALYZERLOTTERY"."USERS" ADD CHECK ("U_USERNAME" IS NOT NULL);
ALTER TABLE "ANALYZERLOTTERY"."USERS" ADD CHECK ("U_PASSWORD" IS NOT NULL);
ALTER TABLE "ANALYZERLOTTERY"."USERS" ADD CHECK ("U_ACTIVE" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table "ANALYZERLOTTERY"."USERS"
-- ----------------------------
ALTER TABLE "ANALYZERLOTTERY"."USERS" ADD PRIMARY KEY ("U_ID");

-- ----------------------------
-- Foreign Key structure for table "ANALYZERLOTTERY"."ASSIGNROLESTOUSER"
-- ----------------------------
ALTER TABLE "ANALYZERLOTTERY"."ASSIGNROLESTOUSER" ADD FOREIGN KEY ("R_ID") REFERENCES "ANALYZERLOTTERY"."ROLES" ("R_ID");
ALTER TABLE "ANALYZERLOTTERY"."ASSIGNROLESTOUSER" ADD FOREIGN KEY ("U_ID") REFERENCES "ANALYZERLOTTERY"."USERS" ("U_ID");

-- ----------------------------
-- Foreign Key structure for table "ANALYZERLOTTERY"."ROLETAKECOMMAND"
-- ----------------------------
ALTER TABLE "ANALYZERLOTTERY"."ROLETAKECOMMAND" ADD FOREIGN KEY ("OC_ID") REFERENCES "ANALYZERLOTTERY"."OPERATIONCOMMAND" ("OC_ID");
ALTER TABLE "ANALYZERLOTTERY"."ROLETAKECOMMAND" ADD FOREIGN KEY ("R_ID") REFERENCES "ANALYZERLOTTERY"."ROLES" ("R_ID");
