/*Drop SEQUENCE*/
DROP SEQUENCE ARU_SEQUENCE;
/*Create SEQUENCE*/
CREATE SEQUENCE ARU_SEQUENCE START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 999999
--CACHE 20
;
/*Call value of SEQUENCE*/
INSERT INTO ASSIGNROLESTOUSER (ARU_ID,R_ID,U_ID) VALUES(ARU_SEQUENCE.nextval,1,'U01');
INSERT INTO ASSIGNROLESTOUSER (ARU_ID,R_ID,U_ID) VALUES(ARU_SEQUENCE.nextval,2,'U01');

INSERT INTO ASSIGNROLESTOUSER (ARU_ID,R_ID,U_ID) VALUES(ARU_SEQUENCE.nextval,0,'U01');
INSERT INTO ASSIGNROLESTOUSER (ARU_ID,R_ID,U_ID) VALUES(ARU_SEQUENCE.nextval,1,'U00');

/*
In ARU_SEQUENCE.nextval where ARU_SEQUENCE is the name of sequence we created above and nextval is a function 
that is used to assign the next number from ARU_SEQUENCE to ARU_ID column in ASSIGNROLESTOUSER table.

EX
--- INCREMENT VALUES---
next value = ARU_SEQUENCE.nextval
--- CURRENT VALUES---
current value = ARU_SEQUENCE.currval

insert into ASSIGNROLESTOUSER (ARU_ID,R_ID,U_ID) values(ARU_SEQUENCE.nextval,'R','U');
*/