/*Drop SEQUENCE*/
DROP SEQUENCE OC_SEQUENCE;
/*Create SEQUENCE*/
CREATE SEQUENCE OC_SEQUENCE START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 999999
--CACHE 20
;
/*Call value of SEQUENCE*/
INSERT INTO OPERATIONCOMMAND (OC_ID,OC_NAME) VALUES(OC_SEQUENCE.nextval,'BUY2');

INSERT INTO OPERATIONCOMMAND (OC_ID,OC_NAME) VALUES(OC_SEQUENCE.nextval,'BUY2');
INSERT INTO OPERATIONCOMMAND (OC_ID,OC_NAME) VALUES(OC_SEQUENCE.nextval,'BUY2');