/*Drop SEQUENCE*/
DROP SEQUENCE RID_SEQUENCE;
/*Create SEQUENCE*/
CREATE SEQUENCE RID_SEQUENCE START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 999999
--CACHE 20
;
/*Call value of SEQUENCE*/
INSERT INTO ROLES (R_ID,R_NAME,R_DESCRIPTION) VALUES(RID_SEQUENCE.nextval,'Administrator','Management and control System.');

INSERT INTO ROLES (R_ID,R_NAME,R_DESCRIPTION) VALUES(RID_SEQUENCE.nextval,'2Numner','Operation 2 number.');
INSERT INTO ROLES (R_ID,R_NAME,R_DESCRIPTION) VALUES(RID_SEQUENCE.nextval,'3Number','Operation 3 number.');