/*
Navicat Oracle Data Transfer
Oracle Client Version : 12.1.0.2.0

Source Server         : LOCAL_LOTTERY
Source Server Version : 110200
Source Host           : localhost:1521
Source Schema         : ANALYZERLOTTERY

Target Server Type    : ORACLE
Target Server Version : 110200
File Encoding         : 65001

Date: 2019-02-16 10:17:20
*/


-- ----------------------------
-- Table structure for "ANALYZERLOTTERY"."ROUND_CONFIGURE"
-- ----------------------------
DROP TABLE "ANALYZERLOTTERY"."ROUND_CONFIGURE";
CREATE TABLE "ANALYZERLOTTERY"."ROUND_CONFIGURE" (
"RCF_ID" VARCHAR2(255 BYTE) NOT NULL ,
"R_YEAR" NUMBER NOT NULL ,
"R_MONTH" NUMBER NOT NULL ,
"R_ROUND" NUMBER NOT NULL ,
"R_STATUS" VARCHAR2(255 BYTE) DEFAULT 'DISABLE'  NOT NULL ,
"MODIFYDATE" DATE DEFAULT SYSDATE  NULL ,
"MODIFYBY" VARCHAR2(255 BYTE) DEFAULT 'SYSTEM'  NULL ,
"CREACTDATETIME" DATE DEFAULT SYSDATE  NULL ,
"CREATEBY" VARCHAR2(255 BYTE) DEFAULT 'SYSTEM'  NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON COLUMN "ANALYZERLOTTERY"."ROUND_CONFIGURE"."R_STATUS" IS 'ACTIVE / DISABLE';

-- ----------------------------
-- Records of ROUND_CONFIGURE
-- ----------------------------
INSERT INTO "ANALYZERLOTTERY"."ROUND_CONFIGURE" VALUES ('20190302', '2019', '3', '2', 'DISABLE', TO_DATE('2019-02-13 17:04:22', 'YYYY-MM-DD HH24:MI:SS'), 'U01', TO_DATE('2019-02-13 15:44:47', 'YYYY-MM-DD HH24:MI:SS'), 'U01');
INSERT INTO "ANALYZERLOTTERY"."ROUND_CONFIGURE" VALUES ('20190202', '2019', '2', '2', 'DISABLE', TO_DATE('2019-02-13 16:43:05', 'YYYY-MM-DD HH24:MI:SS'), 'U01', TO_DATE('2019-02-13 15:43:03', 'YYYY-MM-DD HH24:MI:SS'), 'U01');
INSERT INTO "ANALYZERLOTTERY"."ROUND_CONFIGURE" VALUES ('20190201', '2019', '2', '1', 'DISABLE', TO_DATE('2019-02-13 16:42:14', 'YYYY-MM-DD HH24:MI:SS'), 'U02', TO_DATE('2019-02-13 15:00:57', 'YYYY-MM-DD HH24:MI:SS'), 'U01');
INSERT INTO "ANALYZERLOTTERY"."ROUND_CONFIGURE" VALUES ('20190301', '2019', '3', '1', 'DISABLE', TO_DATE('2019-02-13 16:43:46', 'YYYY-MM-DD HH24:MI:SS'), 'U03', TO_DATE('2019-02-13 15:43:50', 'YYYY-MM-DD HH24:MI:SS'), 'U01');
INSERT INTO "ANALYZERLOTTERY"."ROUND_CONFIGURE" VALUES ('20190401', '2019', '4', '1', 'DISABLE', TO_DATE('2019-02-13 17:06:50', 'YYYY-MM-DD HH24:MI:SS'), 'U02', TO_DATE('2019-02-13 17:04:22', 'YYYY-MM-DD HH24:MI:SS'), 'U01');
INSERT INTO "ANALYZERLOTTERY"."ROUND_CONFIGURE" VALUES ('20190402', '2019', '4', '2', 'ACTIVE', TO_DATE('2019-02-13 17:06:50', 'YYYY-MM-DD HH24:MI:SS'), 'U02', TO_DATE('2019-02-13 17:05:34', 'YYYY-MM-DD HH24:MI:SS'), 'U01');

-- ----------------------------
-- Indexes structure for table ROUND_CONFIGURE
-- ----------------------------
CREATE INDEX "ANALYZERLOTTERY"."RY_AND_RM_INDEX"
ON "ANALYZERLOTTERY"."ROUND_CONFIGURE" ("R_YEAR" ASC, "R_MONTH" ASC)
LOGGING
VISIBLE;
CREATE INDEX "ANALYZERLOTTERY"."R_STATUS_INDEX"
ON "ANALYZERLOTTERY"."ROUND_CONFIGURE" ("R_STATUS" ASC)
LOGGING
VISIBLE;
CREATE INDEX "ANALYZERLOTTERY"."R_YEAR_INDEX"
ON "ANALYZERLOTTERY"."ROUND_CONFIGURE" ("R_YEAR" ASC)
LOGGING
VISIBLE;

-- ----------------------------
-- Checks structure for table "ANALYZERLOTTERY"."ROUND_CONFIGURE"
-- ----------------------------
ALTER TABLE "ANALYZERLOTTERY"."ROUND_CONFIGURE" ADD CHECK ("RCF_ID" IS NOT NULL);
ALTER TABLE "ANALYZERLOTTERY"."ROUND_CONFIGURE" ADD CHECK ("R_YEAR" IS NOT NULL);
ALTER TABLE "ANALYZERLOTTERY"."ROUND_CONFIGURE" ADD CHECK ("R_MONTH" IS NOT NULL);
ALTER TABLE "ANALYZERLOTTERY"."ROUND_CONFIGURE" ADD CHECK ("R_ROUND" IS NOT NULL);
ALTER TABLE "ANALYZERLOTTERY"."ROUND_CONFIGURE" ADD CHECK ("R_STATUS" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table "ANALYZERLOTTERY"."ROUND_CONFIGURE"
-- ----------------------------
ALTER TABLE "ANALYZERLOTTERY"."ROUND_CONFIGURE" ADD PRIMARY KEY ("RCF_ID");
