/*Drop SEQUENCE*/
DROP SEQUENCE RTC_SEQUENCE;
/*Create SEQUENCE*/
CREATE SEQUENCE RTC_SEQUENCE START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 999999
--CACHE 20
;
/*Call value of SEQUENCE*/
INSERT INTO ROLETAKECOMMAND (RTC_ID,OC_ID,R_ID) VALUES(RTC_SEQUENCE.nextval,1,1);

INSERT INTO ROLETAKECOMMAND (RTC_ID,OC_ID,R_ID) VALUES(RTC_SEQUENCE.nextval,1,2);
INSERT INTO ROLETAKECOMMAND (RTC_ID,OC_ID,R_ID) VALUES(RTC_SEQUENCE.nextval,1,3);